# YAML Config Example
## Designed by IoT-devices, LLC - Kyiv - Ukraine
## Website: https://iot-devices.com.ua/en/
## Date: 2024-01-05
esphome:
  name: esp12oled-lm75
  friendly_name: esp12oled-lm75
  comment: "Configuration example of two LM75 for ESP12.OLED_V1 with ESPHome firmware"
  project:
    name: "iot-devices.esp12oled-lm75"
    version: "1.0.0"

external_components:
  - source: github://iotdevicesdev/esphome-lm75
    components: [ lm75 ]

esp8266:
  board: nodemcuv2

logger:

api:
  encryption:
    key: "8tDDLc3S5dnSjADItGR5+7KxoUBhUIqeOiJZIXyyJ"

ota:
  password: "c15e9a44e1408352d945b8cd35b79"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Test-Node Fallback Hotspot"
    password: "rtF1XxDZ9P"

captive_portal:

i2c:
  sda: 4
  scl: 5
  id: i2c_bus

sensor:
  - platform: lm75
    id: temperature
    name: "LM75 temperature"
    update_interval: 30s
    address: 0x48

  - platform: lm75
    id: temperature2
    name: "LM75 temperature2"
    update_interval: 30s
    address: 0x49
# END YAML Config Example
